[package]
name = "rex-svg"
version = "0.1.0"
edition = "2021"

[features]
ttf-parser  = ["dep:ttf-parser", "rex/ttfparser-fontparser"]


[dependencies]
rex = {git = "https://github.com/KenyC/ReX", features = [], default-features = false, rev = "a779adebe63e70ef3b078090373c3af23c8b1083"}


[dependencies.ttf-parser]
version = "*"
optional = true
